# Site settings
title: Platipus
email: admin@platipus.com.br
url: https://platipusc.github.io
description: "Platipus Consultoria que aparece no Google."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E5E5E5
  secondary: 05112E
  secondary-dark: F58200

# Footer settings
footer:
  copyright: Platipus Consultoria
  location: Localização
  social: Mídias sociais

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/platipusc
  - title: github
    url: http://github.com/platipusc

# Postal address (add as many lines as necessary)
address:
  - line: Rua Leopoldo Couto Magalhães Jr.
  - line: 146, 12o andar.
  - line: Itaim Bibi, São Paulo, SP
  - line: CEP 04542-000

# Build settings
markdown: kramdown
permalink: pretty
