# Site settings
title: Platipus
email: admin@platipus.com.br
url: https://platipusc.github.io
description: "Platipus Consultoria que aparece no Google."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2B48A6 #80B3FF
  secondary: FE690C #FD6E8A
  secondary-dark: AA5200 #A2122F

# Footer settings
footer:
  copyright: Platipus Consultoria
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Rua Leopoldo Couto Magalhães Jr., 146
  - line: Itaim Bibi, São Paulo, SP, CEP 04542-000

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
